---
- hosts: localhost
  gather_facts: yes
  vars:
    path_repositories: "{{ ansible_user_dir }}/Repositories"
  tasks:
    - name: requirements
      pip:
        name: docker-py
        state: present
      become: yes

    - name: Remove old container
      docker_container:
        name: DJBot
        image: "krahser/djbot"
        state: absent
      ignore_errors: yes


    - name: create containers
      docker_container:
        name: DJBot
        hostname: DJBot
        image: "krahser/djbot"
        state: started
        restart_policy: always
        ports:
          - "8027:8000"
        volumes:
          - "{{ path_repositories }}/DJBot/:/home/djbot/app"
        env:
          MODE: "dev"
          VIRTUAL_HOST: "dev.djbot.local"
          TZ: Asia/Shanghia[]

    # This is for my specific service
    # - name: restart service
    #   service:
    #     name: DJBot-docker
    #     state: restarted
    #   become: true
