---
- hosts: djbot_demo
  tasks:
    - docker:
        name: djbot
        image: krahser/djbot
        state: started
        restart_policy: always
        env:
          VIRTUAL_HOST: "djbot.local"
          TZ: America/Argentina/Buenos_Aires
